require 'assets/bixbite/Rakefile'

###############################################################################
# 
#	 __PROJECT_NAME__ Build Tasks
#  See assets/bixbite/Rakefile for more information
# 
###############################################################################
