# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bixbite}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Herrera", "Lenny Burdette"]
  s.date = %q{2010-01-03}
  s.default_executable = %q{bixbite}
  s.description = %q{Bixbite is a project initializer for dynamic to static publishing}
  s.email = %q{rich@doctyper.com}
  s.executables = ["bixbite"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "VERSION",
     "lib/bixbite.rb",
     "lib/bixbite/command.rb",
     "lib/bixbite/create.rb",
     "template/Rakefile",
     "template/assets/bixbite/Rakefile.rb",
     "template/assets/naturaldocs/NaturalDocs/Config/Languages.txt",
     "template/assets/naturaldocs/NaturalDocs/Config/Topics.txt",
     "template/assets/naturaldocs/NaturalDocs/Help/customizinglanguages.html",
     "template/assets/naturaldocs/NaturalDocs/Help/customizingtopics.html",
     "template/assets/naturaldocs/NaturalDocs/Help/documenting.html",
     "template/assets/naturaldocs/NaturalDocs/Help/documenting/reference.html",
     "template/assets/naturaldocs/NaturalDocs/Help/documenting/walkthrough.html",
     "template/assets/naturaldocs/NaturalDocs/Help/example/Default.css",
     "template/assets/naturaldocs/NaturalDocs/Help/example/NaturalDocs.js",
     "template/assets/naturaldocs/NaturalDocs/Help/examples.css",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/background.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/leftside.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/logo.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/overbody.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/overbodybg.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/overleftmargin.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/overmenu.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/overmenubg.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/header/rightside.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/logo.gif",
     "template/assets/naturaldocs/NaturalDocs/Help/images/menu/about.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/menu/background.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/menu/bottomleft.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/menu/bottomright.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/menu/community.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/menu/customizing.png",
     "template/assets/naturaldocs/NaturalDocs/Help/images/menu/using.png",
     "template/assets/naturaldocs/NaturalDocs/Help/index.html",
     "template/assets/naturaldocs/NaturalDocs/Help/javascript/BrowserStyles.js",
     "template/assets/naturaldocs/NaturalDocs/Help/javascript/PNGHandling.js",
     "template/assets/naturaldocs/NaturalDocs/Help/keywords.html",
     "template/assets/naturaldocs/NaturalDocs/Help/languages.html",
     "template/assets/naturaldocs/NaturalDocs/Help/menu.html",
     "template/assets/naturaldocs/NaturalDocs/Help/output.html",
     "template/assets/naturaldocs/NaturalDocs/Help/running.html",
     "template/assets/naturaldocs/NaturalDocs/Help/styles.css",
     "template/assets/naturaldocs/NaturalDocs/Help/styles.html",
     "template/assets/naturaldocs/NaturalDocs/Help/troubleshooting.html",
     "template/assets/naturaldocs/NaturalDocs/Info/CSSGuide.txt",
     "template/assets/naturaldocs/NaturalDocs/Info/File Parsing.txt",
     "template/assets/naturaldocs/NaturalDocs/Info/HTMLTestCases.pm",
     "template/assets/naturaldocs/NaturalDocs/Info/Languages.txt",
     "template/assets/naturaldocs/NaturalDocs/Info/NDMarkup.txt",
     "template/assets/naturaldocs/NaturalDocs/Info/Symbol Management.txt",
     "template/assets/naturaldocs/NaturalDocs/Info/images/Logo.png",
     "template/assets/naturaldocs/NaturalDocs/JavaScript/NaturalDocs.js",
     "template/assets/naturaldocs/NaturalDocs/License-GPL.txt",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/BinaryFile.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Builder.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Builder/Base.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Builder/FramedHTML.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Builder/HTML.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Builder/HTMLBase.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/ClassHierarchy.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/ClassHierarchy/Class.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/ClassHierarchy/File.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/ConfigFile.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Constants.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/DefineMembers.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Error.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/File.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/ImageReferenceTable.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/ImageReferenceTable/Reference.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/ImageReferenceTable/String.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/ActionScript.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Ada.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Advanced.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Advanced/Scope.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Advanced/ScopeChange.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Base.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/CSharp.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/PLSQL.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Pascal.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Perl.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Prototype.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Prototype/Parameter.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Simple.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Languages/Tcl.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Menu.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Menu/Entry.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/NDMarkup.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Parser.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Parser/JavaDoc.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Parser/Native.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Parser/ParsedTopic.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Project.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Project/ImageFile.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Project/SourceFile.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/ReferenceString.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Settings.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Settings/BuildTarget.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SourceDB.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SourceDB/Extension.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SourceDB/File.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SourceDB/Item.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SourceDB/ItemDefinition.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SourceDB/WatchedFileDefinitions.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/StatusMessage.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SymbolString.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SymbolTable.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SymbolTable/File.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SymbolTable/IndexElement.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SymbolTable/Reference.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SymbolTable/ReferenceTarget.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SymbolTable/Symbol.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/SymbolTable/SymbolDefinition.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Topics.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Topics/Type.pm",
     "template/assets/naturaldocs/NaturalDocs/Modules/NaturalDocs/Version.pm",
     "template/assets/naturaldocs/NaturalDocs/NaturalDocs",
     "template/assets/naturaldocs/NaturalDocs/NaturalDocs.bat",
     "template/assets/naturaldocs/NaturalDocs/Styles/Default.css",
     "template/assets/naturaldocs/NaturalDocs/Styles/Roman.css",
     "template/assets/naturaldocs/NaturalDocs/Styles/Small.css",
     "template/assets/utilities/White Background in IE 6.txt",
     "template/assets/utilities/pngout",
     "template/deploy/public_html/.htaccess",
     "template/deploy/public_html/.htaccess",
     "template/documentation/js/.htaccess",
     "template/documentation/js/.htaccess",
     "template/src/html/.htaccess",
     "template/src/html/css/cmn/global.css",
     "template/src/html/css/cmn/ie.css",
     "template/src/html/css/cmn/ie6.css",
     "template/src/html/includes/debug.inc",
     "template/src/html/includes/footer.inc",
     "template/src/html/includes/header.inc",
     "template/src/html/includes/html.inc",
     "template/src/html/includes/namespace.inc",
     "template/src/html/includes/page.inc",
     "template/src/html/index.html",
     "template/src/html/js/cmn/bootstrap.js",
     "template/src/html/js/cmn/global.js",
     "template/src/html/js/cmn/lib/LAB.js",
     "template/src/html/min/.htaccess",
     "template/src/html/min/MinifyCLI.php",
     "template/src/html/min/README.txt",
     "template/src/html/min/builder/_index.js",
     "template/src/html/min/builder/bm.js",
     "template/src/html/min/builder/index.php",
     "template/src/html/min/builder/ocCheck.php",
     "template/src/html/min/builder/rewriteTest.js",
     "template/src/html/min/config.php",
     "template/src/html/min/groupsConfig.php",
     "template/src/html/min/index.php",
     "template/src/html/min/lib/FirePHP.php",
     "template/src/html/min/lib/HTTP/ConditionalGet.php",
     "template/src/html/min/lib/HTTP/Encoder.php",
     "template/src/html/min/lib/JSMin.php",
     "template/src/html/min/lib/JSMinPlus.php",
     "template/src/html/min/lib/Minify.php",
     "template/src/html/min/lib/Minify/Build.php",
     "template/src/html/min/lib/Minify/CSS.php",
     "template/src/html/min/lib/Minify/CSS/Compressor.php",
     "template/src/html/min/lib/Minify/CSS/UriRewriter.php",
     "template/src/html/min/lib/Minify/Cache/APC.php",
     "template/src/html/min/lib/Minify/Cache/File.php",
     "template/src/html/min/lib/Minify/Cache/Memcache.php",
     "template/src/html/min/lib/Minify/ClosureCompiler.php",
     "template/src/html/min/lib/Minify/CommentPreserver.php",
     "template/src/html/min/lib/Minify/Controller/Base.php",
     "template/src/html/min/lib/Minify/Controller/Files.php",
     "template/src/html/min/lib/Minify/Controller/Groups.php",
     "template/src/html/min/lib/Minify/Controller/MinApp.php",
     "template/src/html/min/lib/Minify/Controller/Page.php",
     "template/src/html/min/lib/Minify/Controller/Version1.php",
     "template/src/html/min/lib/Minify/HTML.php",
     "template/src/html/min/lib/Minify/ImportProcessor.php",
     "template/src/html/min/lib/Minify/Lines.php",
     "template/src/html/min/lib/Minify/Logger.php",
     "template/src/html/min/lib/Minify/Packer.php",
     "template/src/html/min/lib/Minify/Source.php",
     "template/src/html/min/lib/Minify/YUICompressor.php",
     "template/src/html/min/lib/Solar/Dir.php",
     "template/src/html/min/lib/closure-compiler.jar",
     "template/src/html/min/lib/yuicompressor-2.4.2.jar",
     "template/src/html/min/utils.php",
     "template/src/templates/css/template.css",
     "template/src/templates/js/template.js",
     "template/src/templates/template.html",
     "template/src/yaml/config.yml",
     "template/src/yaml/deploy.yml",
     "template/src/yaml/validate.yml"
  ]
  s.homepage = %q{http://github.com/doctyper/bixbite}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib", "template"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A project initializer for dynamic to static publishing}
  s.test_files = [
    "test/bixbite_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<closure-compiler>, [">= 0.1.5"])
      s.add_runtime_dependency(%q<yui-compressor>, [">= 0.9.1"])
      s.add_runtime_dependency(%q<highline>, [">= 1.5.1"])
    else
      s.add_dependency(%q<closure-compiler>, [">= 0.1.5"])
      s.add_dependency(%q<yui-compressor>, [">= 0.9.1"])
      s.add_dependency(%q<highline>, [">= 1.5.1"])
    end
  else
    s.add_dependency(%q<closure-compiler>, [">= 0.1.5"])
    s.add_dependency(%q<yui-compressor>, [">= 0.9.1"])
    s.add_dependency(%q<highline>, [">= 1.5.1"])
  end
end
